import {
  Sun,
  CloudRain,
  Snowflake,
  Cloud,
  Zap,
  Coffee,
  Briefcase,
  Sparkles,
  Umbrella,
  Wind,
  Flower2,
} from 'lucide-react';

export const WEATHER_OPTIONS = [
  { id: 'sunny', label: 'Sunny', icon: Sun, color: 'text-orange-400' },
  { id: 'rainy', label: 'Rainy', icon: CloudRain, color: 'text-blue-400' },
  { id: 'cold', label: 'Cold', icon: Snowflake, color: 'text-pink-300' },
  { id: 'overcast', label: 'Overcast', icon: Cloud, color: 'text-gray-400' },
];

export const MOOD_OPTIONS = [
  { id: 'energetic', label: 'Active', icon: Zap, color: 'text-rose-500' },
  { id: 'relaxed', label: 'Cozy', icon: Coffee, color: 'text-pink-400' },
  { id: 'productive', label: 'Goal Getter', icon: Briefcase, color: 'text-fuchsia-500' },
  { id: 'chic', label: 'Glam', icon: Sparkles, color: 'text-pink-600' },
  { id: 'romantic', label: 'Romantic', icon: Flower2, color: 'text-red-400' },
  { id: 'formal', label: 'Formal', icon: Umbrella, color: 'text-slate-600' },
  { id: 'funky', label: 'Funky', icon: Wind, color: 'text-purple-500' },
  { id: 'ethereal', label: 'Ethereal', icon: Wind, color: 'text-cyan-400' },
];

export const OOTD_DATA = {
  'sunny-energetic': {
    outfit: 'Ribbed Tank & Biker Shorts',
    shoes: 'Platform Sneakers',
    acc: 'claw clip & sports watch',
    colors: ['#FF85A2', '#FFFFFF', '#FFD1DC'],
    description: 'Perfect for a morning coffee run or a light workout under the sun.',
  },
  'sunny-relaxed': {
    outfit: 'Flowy Mini Skirt & Baby Tee',
    shoes: 'Woven Mules',
    acc: 'Tote bag & sunnies',
    colors: ['#FADADD', '#FFF5F5', '#E9967A'],
    description: 'A breezy, effortless look for a casual weekend stroll.',
  },
  'sunny-productive': {
    outfit: 'Linen Trousers & Cropped Vest',
    shoes: 'Pointed Slingbacks',
    acc: 'Structured handbag',
    colors: ['#FFFFFF', '#D8BFD8', '#F8BBD0'],
    description: 'Stay cool and focused during meetings or errands.',
  },
  'sunny-chic': {
    outfit: 'Satin Slip Dress & White Cardigan',
    shoes: 'Strappy Sandals',
    acc: 'Gold hoops & dainty rings',
    colors: ['#FFC0CB', '#FBC2EB', '#FFD700'],
    description: 'Glowing and elegant for a brunch or photo-op.',
  },
  'sunny-romantic': {
    outfit: 'Milkmaid Sundress & Lace Socks',
    shoes: 'Mary Janes',
    acc: 'Floral hair ribbon',
    colors: ['#FFF0F5', '#FFB6C1', '#FFFFFF'],
    description: 'A dreamy aesthetic for a garden date or picnic.',
  },
  'sunny-formal': {
    outfit: 'Pencil Skirt & Silk Blouse',
    shoes: 'Stiletto Heels',
    acc: 'Pearl necklace',
    colors: ['#F5F5F5', '#E6E6FA', '#000000'],
    description: 'Sophisticated elegance for high-stakes daytime events.',
  },
  'sunny-funky': {
    outfit: 'Graphic Tee & Patchwork Denim',
    shoes: 'Chunky Platform Boots',
    acc: 'Colored sunglasses',
    colors: ['#FF00FF', '#00FFFF', '#FFFF00'],
    description: 'Bold, expressive, and ready to stand out.',
  },
  'sunny-ethereal': {
    outfit: 'Sheer Maxi Skirt & Corset Top',
    shoes: 'Lace-up Sandals',
    acc: 'Butterfly clips',
    colors: ['#E0FFFF', '#F0F8FF', '#FFFFFF'],
    description: 'Float through the day like a modern-day fairy.',
  },
  'rainy-energetic': {
    outfit: 'Parachute Pants & Zip-up Hoodie',
    shoes: 'Water-resistant Trainers',
    acc: 'Clear umbrella',
    colors: ['#FF007F', '#2D3436', '#A29BFE'],
    description: 'Keep your energy up even when the sky is grey.',
  },
  'rainy-relaxed': {
    outfit: 'Knit Co-ord Set',
    shoes: 'Classic Uggs',
    acc: 'Cute beanie',
    colors: ['#E6A8D7', '#D1D1D1', '#F7E7CE'],
    description: 'Maximum comfort for a cozy rainy day vibe.',
  },
  'rainy-productive': {
    outfit: 'Blazer & Straight Leg Denim',
    shoes: 'Ankle Rain Boots',
    acc: 'Designer backpack',
    colors: ['#636E72', '#FF85A2', '#000000'],
    description: 'Professional and polished while staying dry.',
  },
  'rainy-chic': {
    outfit: 'Belted Trench & Tall Leather Boots',
    shoes: 'Patent Leather Heels',
    acc: 'Headband & pearls',
    colors: ['#F5F5DC', '#FF1493', '#000000'],
    description: 'Total main character energy for a rainy city walk.',
  },
  'rainy-romantic': {
    outfit: 'Velvet Dress & Fleece Tights',
    shoes: 'Chelsea Boots',
    acc: 'Beret',
    colors: ['#800020', '#000000', '#D3D3D3'],
    description: 'Moodily romantic for a rainy cafe date.',
  },
  'rainy-formal': {
    outfit: 'Tweed Suit & Silk Scarf',
    shoes: 'Leather Loafers',
    acc: 'Gold watch',
    colors: ['#2F4F4F', '#FFB6C1', '#FFFFFF'],
    description: 'Sharp and protected from the drizzle.',
  },
  'rainy-funky': {
    outfit: 'Bright Raincoat & Vinyl Skirt',
    shoes: 'Neon Wellies',
    acc: 'Bucket hat',
    colors: ['#39FF14', '#FF007F', '#000000'],
    description: 'Bringing the color to a gloomy day.',
  },
  'rainy-ethereal': {
    outfit: 'Tulle Layered Skirt & Mesh Top',
    shoes: 'Clear Rain Boots',
    acc: 'Silver hair pins',
    colors: ['#B0C4DE', '#F0F8FF', '#778899'],
    description: 'Ethereal vibes meet rain-soaked streets.',
  },
  'cold-energetic': {
    outfit: 'Cropped Puffer & Leggings',
    shoes: 'Hiking Style Boots',
    acc: 'Ear muffs',
    colors: ['#FF007F', '#FFFFFF', '#000000'],
    description: 'Stay warm and ready for winter adventures.',
  },
  'cold-relaxed': {
    outfit: 'Oversized Knit & Fleece Tights',
    shoes: 'Fluffy Slides',
    acc: 'Scarf & mittens',
    colors: ['#FFB6C1', '#FDFD96', '#C1E1C1'],
    description: 'Soft girl winter aesthetic at its finest.',
  },
  'cold-productive': {
    outfit: 'Long Wool Coat & Turtleneck Dress',
    shoes: 'Over-the-knee Boots',
    acc: 'Leather gloves',
    colors: ['#30336B', '#FADADD', '#130F40'],
    description: 'Sleek and professional for cold morning commutes.',
  },
  'cold-chic': {
    outfit: 'Faux Fur Jacket & Mini Skirt',
    shoes: 'Square-toe Boots',
    acc: 'Beret & small clutch',
    colors: ['#FF69B4', '#FFFFFF', '#000000'],
    description: 'A luxurious winter look for dinner or a party.',
  },
  'cold-romantic': {
    outfit: 'Cashmere Set & Satin Ribbon',
    shoes: 'Fur-lined Mules',
    acc: 'Heart jewelry',
    colors: ['#FFC0CB', '#FFFFFF', '#FFD700'],
    description: 'Warm hearts on a cold winter day.',
  },
  'cold-formal': {
    outfit: 'Tailored Overcoat & Wide-leg Slacks',
    shoes: 'Pointed Boots',
    acc: 'Minimalist bag',
    colors: ['#000000', '#F5F5F5', '#C0C0C0'],
    description: 'High-fashion winter corporate look.',
  },
  'cold-funky': {
    outfit: 'Neon Puffer & Patterned Knits',
    shoes: 'Moon Boots',
    acc: 'Clunky headphones',
    colors: ['#FF00FF', '#000000', '#00FF00'],
    description: 'Streetwear maximalism for the cold.',
  },
  'cold-ethereal': {
    outfit: 'White Faux Fur & Silky Midi',
    shoes: 'Glitter Heels',
    acc: 'Tiara headband',
    colors: ['#FFFFFF', '#F0FFFF', '#E6E6FA'],
    description: 'Looking like a literal winter queen.',
  },
  'overcast-energetic': {
    outfit: 'Varsity Jacket & Cargo Skirt',
    shoes: 'Chunky Loafers',
    acc: 'Crossbody bag',
    colors: ['#FF4D6D', '#DFE6E9', '#2D3436'],
    description: 'Street-style ready for a moody sky.',
  },
  'overcast-relaxed': {
    outfit: 'Wide-leg Sweatpants & Crop Top',
    shoes: 'Platform Slides',
    acc: 'Baseball cap',
    colors: ['#FFD1DC', '#B2BEC3', '#FFFFFF'],
    description: 'The "Clean Girl" aesthetic for a low-key day.',
  },
  'overcast-productive': {
    outfit: 'Matching Tweed Set',
    shoes: 'Mary Janes',
    acc: 'Studded earrings',
    colors: ['#D8BFD8', '#FADADD', '#6D214F'],
    description: 'Sophisticated and chic for achieving your goals.',
  },
  'overcast-chic': {
    outfit: 'Pleated Midi & Fitted Sweater',
    shoes: 'Kitten Heels',
    acc: 'Silk hair ribbon',
    colors: ['#A29BFE', '#FADADD', '#FFFFFF'],
    description: 'A romantic, soft-toned look for diffused lighting.',
  },
  'overcast-romantic': {
    outfit: 'Soft Knit Dress & Bows',
    shoes: 'Ankle Boots',
    acc: 'Lace choker',
    colors: ['#E9967A', '#FADADD', '#FFFFFF'],
    description: 'Moody yet sweet for a cloudy afternoon.',
  },
  'overcast-formal': {
    outfit: 'Grey Blazer & Matching Shorts',
    shoes: 'Oxfords',
    acc: 'Briefcase',
    colors: ['#708090', '#FFFFFF', '#000000'],
    description: 'Modern professional vibes.',
  },
  'overcast-funky': {
    outfit: 'Animal Print Coat & Leather Pants',
    shoes: 'Combat Boots',
    acc: 'Chain belt',
    colors: ['#000000', '#FFD700', '#8B4513'],
    description: 'Bold textures for a grey-sky day.',
  },
  'overcast-ethereal': {
    outfit: 'Layered Mesh Dress',
    shoes: 'Ballet Flats',
    acc: 'Silver rings',
    colors: ['#DCDCDC', '#FFFFFF', '#B0C4DE'],
    description: 'A soft, ghostly beauty under the clouds.',
  },
};
